name: Fetch News Data  # 뉴스 데이터 수집

on: 
  schedule: 
    - cron: "0 23 * * *"  # 매 분마다 실행 (스케줄 변경 가능)
  workflow_dispatch:  # 수동 실행 가능
  push:  
    branches: 
      - main  # main 브랜치에 push 발생 시 실행

jobs:
  fetch_news:
    runs-on: ubuntu-latest  # 최신 우분투 환경에서 실행

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3  # 현재 GitHub 저장소를 clone
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub 권한 사용

      - name: Python 설정
        uses: actions/setup-python@v4  # Python 설치
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests
          pip install numpy
          pip install scipy==1.10.1
          pip install gensim==3.8.3
      - name: Install Chrome
        run: |
          set -ex
          sudo apt-get update -y
          wget <https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb>
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          sudo apt-get install -y -f
      - name: Setup ChromeDriver
        run: |
          wget <https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.58/linux64/chromedriver-linux64.zip>
          unzip chromedriver-linux64.zip
          sudo mv ./chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
      - name: Setup Xvfb
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99

      - name: 뉴스 데이터 크롤링 및 저장
        run: python news_script.py  # 웹 크롤링을 실행하는 Python 스크립트 실행

      - name: 변경 사항 커밋 및 푸시
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-action@github.com"
          git add *.db  # 모든 .db 파일 추가
          git commit -m "Update news data (auto)" || echo "No changes to commit"
          git push
